#!/bin/bash

function fun1()
{
	echo $1
	echo $2
	echo $3
}
function fun()
{
	echo $1
	echo $2
	echo $3
	fun1 $1 $2 $3
}
if [ $# -gt 1 ]
then 
if [ $2 = "-h" ]
then 

	echo "----------------------"
	echo "usage :"
	echo "call + cmd + arg"
	echo "----------------------"
	echo "info:"
	type -a $1 
	echo "----------------------"
	echo "content:"
	cat /root/repo-github/bin/$1
	echo "----------------------"
else
 	$1 $2
fi
fi
