#!/bin/bash

ARG_NO=$#
ARGS=$@
echo  arg no:$ARG_NO  args: $ARGS
ARGS_CMD=`echo $ARGS|sed "s/^**/ppp/g"`
echo rst  $ARGS_CMD
$ARGS
#function fun_help()
#{
#	echo "----------------------"
#	echo "usage :"
#	echo "call + cmd + arg"
#	echo "----------------------"
#	echo "info:"
#	type -a $1 
#	echo "----------------------"
#	echo "content:"
#	cat /root/repo-github/bin/$1
#	echo "----------------------"
#}

function fun_help()
{
    $1 -h
}
function fun_exec()
{
 	$1 $2
}
function fun_exec_withoutarg()
{
 	$1 
}
if [ $# -gt 1 ] && [ $2 = "-h" ]
then 	
 	fun_help $1
else
	fun_exec $1 $2
fi

